### ISSUE TITLE
Test code Error

### ISSUE THREAD

**Issue by dingzex** [DmitrySoshnikov/hdl-js#34]
I run the test under windows and find an error. What is the reason?

F:\hdl-js>node bin/hdl-js -g examples/MipsAlu16.hdl -e '[{a: 2, b: 3, op: 2}]' -f dec -c a,b,out
evalmachine.<anonymous>:1
('[{a:)
 ^^^^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInNewContext (vm.js:135:10)
    at parseInputData (F:\hdl-js\dist\bin\hdl-js-cli.js:117:19)
    at loadAndProcessData (F:\hdl-js\dist\bin\hdl-js-cli.js:110:10)
    at main (F:\hdl-js\dist\bin\hdl-js-cli.js:520:16)
    at Object.<anonymous> (F:\hdl-js\bin\hdl-js:5:34)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by DmitrySoshnikov** [comment]
Hi, on Windows please try using double-quotes and escaping; try also using actual JSON with properties in strings.
